### ISSUE TITLE
Perun VOs listed as "group"

### ISSUE THREAD

**Issue by sebastian-luna-valero** [tdviet/fedcloudclient#54] opened 2021-08-03 09:31 UTC
Hi,

When I run:
```
fedcloud token list-vos
```

All my Perun VOs are shown as `group`.

The Perun VOs are correctly listed in https://aai.egi.eu/oidc/manage/user/profile and https://perun.egi.eu/egi/gui/

Is this an issue with `fedcloudclient` or with Perun?

Many thanks,
Sebastian

**Comment by tdviet** [comment] 2021-08-03 09:56
Hi Sebastian,

there are some ongoing changes in Perun, and the ":group" substring is duplicated in the eduperson_entitlement for Perun VOs. I am not sure it is a bug or intentional. 

Normal VOs in Check-in:
urn:mace:egi.eu:group:acc-comp.egi.eu:role=vm_operator#aai.egi.eu 
urn:mace:egi.eu:group:eosc-synergy.eu:role=member#aai.egi.eu

VOs in Perun with ":group:group":
urn:mace:egi.eu:group:group:fedcloud.egi.eu:role=member#aai.egi.eu
urn:mace:egi.eu:group:group:demo.fedcloud.egi.eu:role=member#aai.egi.eu

Strangely, the training.egi.eu VO is managed by Perun, too, but it is correct
urn:mace:egi.eu:group:training.egi.eu:role=member#aai.egi.eu

@enolfc: What is the status of Perun integration?

**Comment by enolfc** [comment] 2021-08-17 11:32
@tdviet I was unaware of this change, just added you to some communication with Check-in

**Comment by NicolasLiampotis** [comment] 2021-08-17 11:36
@tdviet This was a bug introduced by the Check-in IdP/SP Proxy upgrade implemented on the 22nd of July. The extra "group" literal was erroneously added by the Check-in proxy to VO/group entitlements from Perun. Entitlements for VOs managed in COmanage Registry were not affected. The bug was fixed today at 8:57 AM.

Note that the training.egi.eu VO is a special case since it is managed by both Perun and COmanage Registry.

**Comment by tdviet** [comment] 2021-08-17 11:41
Thanks @NicolasLiampotis  and @enolfc. The problem is solved, VOs are now correctly shown, so I close this issue.

**Closed by tdviet** 2021-08-17 11:41 UTC
Labels: question
